apiVersion: apps/v1
kind: Deployment

metadata:
  name: game2048

spec:
  replicas: 1

  selector:
    matchLabels:
      app: game2048

  template:
    metadata:
      labels:
        app: game2048

    spec:
      containers:
      - name: game2048
        image: ranjithreddy144/game2048:latest
        imagepullpolicy: Always
        ports:
        - containerPort: 8080