name: CI-CD Pipeline

on:
 push:
  branches:
   - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest


steps:
  - name: Checkout Source
    uses: actions/checkout@v4

  - name: Setup Java
    uses: actions/setup-java@v4
    with:
      distribution: temurin
      java-version: 21

  - name: Run Tests
    run: mvn test

  - name: Build Jar
    run: mvn clean package -DskipTests

  - name: Login DockerHub
    uses: docker/login-action@v3
    with:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

  - name: Build Image
    run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/game2048:latest .

  - name: Push Image
    run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/game2048:latest


deploy:
  needs: build-and-push
  runs-on: self-hosted


steps:
  - name: Pull Latest Image
    run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/game2048:latest

  - name: Update Deployment
    run: kubectl set image deployment/game2048 game2048=${{ secrets.DOCKERHUB_USERNAME }}/game2048:latest

  - name: Verify Rollout
    run: kubectl rollout status deployment/game2048

  - name: Check Pods
    run: kubectl get pods

